export const projects = [
  {
    title: 'CryptoVerse',
    description: "An all in one crypto currency dashboard for real crypto enthusiasts. It features live data from the GCCM. As well as top news from trusted sources.",
    image: '/images/project8.png',
    tags: ['React', 'Redux-Toolkit', 'CSS', 'antdesign'],
    source: 'https://cryptoverses.netlify.app/',
    visit: 'https://github.com/edisonabdiel/cryptoVerse',
    id: 0,
  },
  {
    title: 'CogBlog',
    description: "My most ambitious project so far. CogBlog is a modern and fully fuctional blog for fictional characters who are also aspiring writters. Built with state-of-the-art technologies.",
    image: '/images/project10.png',
    tags: ['React', 'TypeScript', 'GraphQL', 'TailwindCSS', 'Next.JS'],
    source: 'https://cog-blog.vercel.app/',
    visit: 'https://github.com/edisonabdiel/CogBlog',
    id: 1,
  },
  {
    title: 'Chairs 3D',
    description: "Yet another project showcasing the power of Three.js. This one in particular goes more into exploring Surface Sampling using the the MeshSurfaceSampler to create interesting effects on the 3D models.",
    image: '/images/project7.png',
    tags: ['React', 'Three.js', 'React-Three-Fiber', 'CSS', 'Drei'],
    source: 'https://3dchairs.netlify.app/',
    visit: 'https://github.com/edisonabdiel/3d-Chairs',
    id: 2,
  },
  {
    title: 'GPT-3 by OpenAI',
    description: "Just an awesome looking landing page for the OpenAI project called GPT-3. What is special about this project is that it was styled 100% with vanilla CSS to showcase they power of the BEM methodology",
    image: '/images/project11.png',
    tags: ['React', 'CSS'],
    source: 'https://gpt-3.netlify.app/',
    visit: 'https://github.com/edisonabdiel/GTP-3-LandingPage',
    id: 3,
  },
  {
    title: 'StoryMe',
    description: "A social platform for users to post short stories and poems. A fully funtional MERN app with its designated API and OAuth system. Styled with SASS + Material UI components.",
      image: '/images/project3.png',
      tags: ['React', 'MongoDB', 'Node.js', 'Material UI'],
    source: 'https://storyme-app.herokuapp.com/',
    visit: 'https://github.com/edisonabdiel/StoryMe',
    id: 4,
  },
  {
    title: 'React Weather',
    description: "A fully functional weather forecast app made with React and openweathermap.org. It features a neat search bar and a set of weather recommendations as well as a light and dark mode toggle function.",
    image: '/images/project5.png',
    tags: ['React', 'lodash', 'Tailwind-css'],
    source: 'https://react-weather-edison.netlify.app/',
    visit: 'https://github.com/edisonabdiel/React-Weather',
    id: 5,
  },
  {
    title: 'Surface Sampling 3D Showcase',
    description: "Yet another project showcasing the power of Three.js. This one in particular goes more into exploring Surface Sampling using the the MeshSurfaceSampler to create interesting effects on the 3D models.",
    image: '/images/project6.png',
    tags: ['JavaScript', 'Three.js', 'HTML', 'CSS'],
    source: 'https://surface-sampling.netlify.app/',
    visit: 'https://github.com/edisonabdiel/SurfaceSampling',
    id: 6,
  },
  {
    title: 'SmartXpense',
    description:"A modern expense tracker integrated with Speechly's voice recognition features. It manages several states with Context API and uses web components from Material UI",
    image: '/images/project9.png',
    tags: ['React', 'Context API', 'Framer Motion', 'Material-UI'],
    source: 'smart-xpense.netlify.app',
    visit: 'https://github.com/edisonabdiel/SmartXpense',
    id: 7,
  },
  {
    title: 'Framer Motion Online Shop',
    description:"A cute little Online Shop showcasing the power of Framer Motion and vanilla CSS. All the elements in the page have been animated, giving life and a neat-modern feeling to the app.",
    image: '/images/project2.png',
    tags: ['React', 'NEXT.js', 'Framer Motion', 'SCSS'],
    source: 'https://google.com',
    visit: 'https://github.com/edisonabdiel/Shopper',
    id: 8,
  },
  {
    title: 'Jelly Shapes',
    description: "A neat wobbly demo about the power of Three.js + React-Fiber-Three. The shapes are clickable and zoomable, cast shadows and they also wobble just like jelly. Only the tip of the icerberg of what can be achieved with Three.js and Fiber.",
    image: '/images/project4.png',
    tags: ['React', 'Three.js', 'React-Fiber-Three', 'SASS'],
    source: 'https://jelly-shapes.netlify.app/',
    visit: 'https://github.com/edisonabdiel/Jelly-Shapes3D',
    id: 9,
  },
  
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey with my first programming language: SQL.', },
  { year: 2018, text: 'Made my first GitHub PR. Started diving into HTML, CSS, JavaScript and its ecosystem. Started my first bootcamp', },
  { year: 2019, text: 'Developed my first (of several) tool from scratch, regularly used by one of the operational teams at SoundCloud. Started my second bootcamp.', },
  { year: 2020, text: 'Became a full-time Software Engineer at SoundCloud.', },
  { year: 2021, text: 'Solidfied my frontend experience. Flew the nest in direction towards my next big professional adventure.', },
  { year: 2022, text: 'Began my new challange as a full-time React Softwre Engineer at Aronfhome', },
];